import "/public/icons/icomoon/style.css"
import "/public/css/bootstrap.css"
import "/public/css/animate.min.css"
import "/public/css/odometer.min.css"
import "/public/css/swiper-bundle.min.css"
import "/public/scss/app.scss"
import { Archivo } from 'next/font/google'

const archivo = Archivo({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    variable: "--font-main",
    display: 'swap',
})
export const metadata = {
    title: 'Healingy - Therapy & Counseling Psychologist Next.js Template',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${archivo.variable}`}>{children}</body>
        </html>
    )
}


